function [R] = RHS(t,x,constants,Pressure,dx,h_bc,u_bc)
%Builds my RHS for my 1st continuity Equation
R_Ideal=constants(1);
MW=constants(2);
P0=constants(3);
DP=constants(4);
R=constants(5);
T_surr=constants(6);
Cp = constants(7);
U =constants(8);
Ff=constants(9);
Per = constants(10);
A = constants(11);
mu = constants(12);
k = constants(13);
m_flow=constants(14);
uoffset= constants(15);
hoffset= constants(16);
Toffset = constants(17);
rhooffset = constants(18);
Poffset = constants(19);
Elements=constants(20);
dgnodes=constants(21);
R=zeros(4*dgnodes,1);
R(1:dgnodes-1)=RHS_Enth(t,x,constants,dx);
R(dgnodes:2*dgnodes-2)=RHS_Cont(t,x,constants,dx);
R(2*dgnodes-1:2*dgnodes)=RHS_BC(x,constants,h_bc,u_bc);
R(2*dgnodes+1:3*dgnodes)=RHS_Density(x,constants,Pressure);
R(3*dgnodes+1:4*dgnodes)=RHS_Temp(x,constants);
end