function [Enth] = Enthalpy_Term(x,constants)
%Builds my RHS for my 1st continuity Equation
R_Ideal=constants(1);
MW=constants(2);
P0=constants(3);
DP=constants(4);
R=constants(5);
T_surr=constants(6);
Cp = constants(7);
U =constants(8);
Ff=constants(9);
Per = constants(10);
A = constants(11);
mu = constants(12);
k = constants(13);
m_flow=constants(14);
uoffset= constants(15);
hoffset= constants(16);
Toffset = constants(17);
rhooffset = constants(18);
Poffset = constants(19);
Elements=constants(20);
dgnodes=constants(21);
Enth=zeros(dgnodes,1);
i=1;
Enth(2)=A*x(rhooffset+2*i)*x(uoffset+2*i)*x(hoffset+2*i)-...
    A/12*(3*x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+....   
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i)+...
          3*x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i));
           
for i=2:Elements
    Enth(2*i-1)=-A*x(rhooffset+2*(i-1))*x(uoffset+2*(i-1))*x(hoffset+2*(i-1))+...
     A/12*(3*x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+....   
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i)+...
          3*x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i));
    
             
    Enth(2*i)=A*x(rhooffset+2*i)*x(uoffset+2*i)*x(hoffset+2*i)-...
    A/12*(3*x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i-1)+....   
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i-1)+...
          x(rhooffset+2*i)*x(hoffset+2*i-1)*x(uoffset+2*i)+...
          x(rhooffset+2*i-1)*x(hoffset+2*i)*x(uoffset+2*i)+...
          3*x(rhooffset+2*i)*x(hoffset+2*i)*x(uoffset+2*i));
end
Enth=Enth(2:end);
end

